#server:
#  servlet:
#    context-path: /demo
#  port: 9090
#
#spring:
#  messages:
#    basename: messages/messages
#  datasource:
#    url: jdbc:postgresql://localhost:5432/warehouse
#    username: postgres
#    password: root
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
